services:
  engine:
    image: ghcr.io/5minds/processcube_engine:18.6.8-extensions-2.5.1-beta.2
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8000:8000
    volumes:
      - ./.processcube/engine/db:/database
      - ./processes:/processes:ro
    environment:
      - application__name=ProcessCube.App.SDK Test App
      - database__dialect=postgres
      - database__host=postgres
      - database__port=5432
      - database__username=postgres
      - database__password=postgres
      - database__database=engine
      - httpServer__port=8000
      - iam__baseUrl=http://authority:11560
    command: --seed-dir=/processes
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 5s
      retries: 10
      timeout: 10s

  authority:
    image: 5minds/processcube_authority:3.1.2
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 11560:11560
    volumes:
      - ./.processcube/authority/config/config.json:/etc/authority/config/config.json
      - ./.processcube/authority/config/upeSeedingData.json:/etc/authority/upeSeedingData.json
    environment:
      - CONFIG_PATH=/etc/authority/config/config.json
      - UPE_SEED_PATH=/etc/authority/upeSeedingData.json

  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.processcube/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 10
      timeout: 10s
    restart: unless-stopped
