name: 'PR Tasks Completed Check'
on:
  pull_request:
    types: [opened, edited]

jobs:
  task-check:
    runs-on: ubuntu-latest
    if: github.actor != 'renovate'
    steps:
      - uses: kentaro-m/task-completed-checker-action@v0.1.2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
