name: Verify Build and Publish

on:
  push:
    branches:
      - main
      - next
      - develop
      - 'release/**'
    tags:
      - 'v*.*.*'
  pull_request:
  workflow_dispatch:

env:
  CI_TOOLS_VERSION: '^5.0.0'
  # NOTE: Um die Entwicklungsphase von Alpha nach Beta zu Ã¤ndern, einfach die nachfolgend deklarierten Env Variablen switchen.
  CI_TOOLS_ALPHA_BRANCH: next
  CI_TOOLS_ALPHA_NPM_TAG: next
  # CI_TOOLS_BETA_BRANCH: next
  # CI_TOOLS_BETA_NPM_TAG: next
  BOX_RELEASE_TAG: 2025-2

jobs:
  verify:
    name: 'Verify and format code'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Format code
        run: npm run format

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain | grep -v '^.* \.github/workflows/')" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.name "process-engine-ci"
          git config --local user.email "process-engine-ci@5minds.de"
          git add . ':(exclude).github/workflows/*'
          git commit -m "style: apply prettier formatting [skip ci]"
          git push origin HEAD:${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_and_publish:
    name: 'Build and publish sources'
    runs-on: ubuntu-latest
    needs: verify

    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Use Node.js 22
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Install CI Tools
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm i -g @5minds/product_ci_tools@${{ env.CI_TOOLS_VERSION }}

      - name: 'Install Dependencies'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm ci

      - name: Prepare version
        run: ci_tools prepare-version --allow-dirty-workdir

      - name: Commit and Tag Version
        env:
          GH_USER: ${{ secrets.GH_USER }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: ci_tools commit-and-tag-version --only-on-primary-branches

      - name: Build Packages
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Publish Version
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: ci_tools publish-npm-package --create-tag-from-branch-name

      - name: Add Box-Release Tag
        if:  ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/next' }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          VERSION="$(ci_tools get-version)"
          npm dist-tag add @5minds/processcube_app_sdk@$VERSION ${{ env.BOX_RELEASE_TAG }}


